import { FormEvent, useEffect, useState } from "react";

type Campaign={id:string;platform:string;name:string;status:string;niche:string;rules:string};
const API=import.meta.env.VITE_CAMPAIGNS_API_URL||"http://127.0.0.1:8775";
const tabs=["Campanhas","Fontes e materiais","Produção","Revisão","Publicações e rascunhos","Contas e canais","Resultados","Auditoria e configurações"];
const input="min-h-11 rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2";
export function CampanhasCortes(){
 const [tab,setTab]=useState(0),[token,setToken]=useState(()=>sessionStorage.getItem("campaigns_token")||""),[draft,setDraft]=useState(""),[items,setItems]=useState<Campaign[]>([]),[error,setError]=useState("");
 const [form,setForm]=useState({platform:"manual",name:"",url:"",niche:"",status:"draft",starts_at:null,ends_at:null,reward_model:"",reward_value:0,budget:0,networks:["tiktok"],rules:"",hashtags:[],mentions:[],target_profile:"",duplicate_policy:"deny",automation_policy:"manual-only"});
 async function request(path:string,init:RequestInit={}){const r=await fetch(API+path,{...init,headers:{"Content-Type":"application/json","X-Campaigns-Token":token}});if(!r.ok)throw new Error(await r.text());return r.json()}
 async function refresh(){try{setItems(await request("/campaigns/v1/campaigns"));setError("")}catch(e){setError(e instanceof Error?e.message:"Falha")}}
 useEffect(()=>{if(token)void refresh()},[token]);
 function login(e:FormEvent){e.preventDefault();sessionStorage.setItem("campaigns_token",draft);setToken(draft)}
 async function save(e:FormEvent){e.preventDefault();try{await request("/campaigns/v1/campaigns",{method:"POST",body:JSON.stringify(form)});setForm({...form,name:"",url:"",rules:""});await refresh()}catch(e){setError(e instanceof Error?e.message:"Falha")}}
 const panel="rounded-2xl border border-zinc-800 bg-zinc-900/75 p-4";
 if(!token)return <form onSubmit={login} className={`${panel} mx-auto max-w-md space-y-3`}><h1 className="text-2xl font-bold">Campanhas de Cortes</h1><p className="text-sm text-zinc-400">Agente local isolado, dry-run e sem publicação externa.</p><input className={`${input} w-full`} type="password" placeholder="Token local" value={draft} onChange={e=>setDraft(e.target.value)} required/><button className="min-h-11 w-full rounded-lg bg-cyan-500 font-bold text-zinc-950">Conectar</button></form>;
 return <main className="space-y-4" data-testid="campaigns-module"><header className={panel}><p className="text-xs font-bold uppercase tracking-widest text-cyan-400">Feature flag · dry-run</p><h1 className="text-2xl font-bold">Campanhas de Cortes</h1><p className="text-sm text-zinc-400">Controle local; aprovação, métricas e pagamentos permanecem nas plataformas.</p><nav className="mt-4 flex gap-2 overflow-x-auto">{tabs.map((x,i)=><button key={x} onClick={()=>setTab(i)} className={`min-h-10 whitespace-nowrap rounded-lg px-3 ${tab===i?"bg-cyan-500 text-zinc-950":"border border-zinc-700"}`}>{x}</button>)}</nav></header>{error&&<div role="alert" className="rounded-lg border border-red-700 p-3">{error}</div>}
 {tab===0?<section className={`${panel} space-y-4`}><form onSubmit={save} className="grid gap-2 md:grid-cols-3"><select className={input} value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}><option value="networking-club">Networking Club</option><option value="viewx">ViewX</option><option value="manual">Outra (manual)</option></select><input className={input} placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className={input} placeholder="Nicho" value={form.niche} onChange={e=>setForm({...form,niche:e.target.value})}/><input className={input} type="url" placeholder="URL HTTPS" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/><textarea className={`${input} md:col-span-2`} placeholder="Regras, direitos, hashtags e restrições" value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})}/><button className="rounded-lg bg-cyan-500 font-bold text-zinc-950">Cadastrar</button></form><div className="grid gap-3 md:grid-cols-2">{items.map(x=><article key={x.id} className="rounded-xl border border-zinc-800 p-3"><strong>{x.name}</strong><p className="text-sm text-zinc-400">{x.platform} · {x.niche||"sem nicho"} · {x.status}</p><p className="mt-2 text-sm">{x.rules||"Regras pendentes"}</p></article>)}</div></section>:<section className={panel}><h2 className="text-lg font-bold">{tabs[tab]}</h2><p className="mt-2 text-zinc-400">Área isolada preparada para o fluxo do MVP, com auditoria, revisão humana, limites próprios e nenhuma ação externa real.</p></section>}</main>
}
