import {useEffect,useRef,useState} from "react";
import type {FormEvent,ReactNode} from "react";
type Product={id:string;name:string;category:string;price:number};
type Media={id:string;product_id:string|null;kind:"video"|"audio";name:string;local_path:string;duration_seconds:number;authorized:boolean;authorization_source:string};
type Script={id:string;product_id:string;kind:string;position:number;duration_seconds:number;text:string};
type Session={id:string;title:string;estimated_minutes:number;product_ids:string[];status:string;seed:number};
type Material={media_id:string;position:number;planned_duration_seconds:number};
type LiveEvent={type:string;payload:Record<string,unknown>};
const API=import.meta.env.VITE_SHOP_LIVE_API_URL||"http://127.0.0.1:8765";
const box="rounded-xl border border-zinc-800 bg-zinc-900/70 p-4";
const input="rounded border border-zinc-700 bg-zinc-950 p-2";
export function ShopLive(){
 const socket=useRef<WebSocket|null>(null); const [token,setToken]=useState(()=>sessionStorage.getItem("shop_live_token")||""); const [draft,setDraft]=useState("");
 const [products,setProducts]=useState<Product[]>([]),[media,setMedia]=useState<Media[]>([]),[scripts,setScripts]=useState<Script[]>([]),[sessions,setSessions]=useState<Session[]>([]),[materials,setMaterials]=useState<Material[]>([]);
 const [selectedProduct,setSelectedProduct]=useState(""),[selectedSession,setSelectedSession]=useState(""),[state,setState]=useState("offline"),[context,setContext]=useState<Record<string,any>>({});
 const headers={"Content-Type":"application/json","X-Shop-Live-Token":token};
 async function request(path:string,init:RequestInit={}){const response=await fetch(API+path,{...init,headers:{...headers,...init.headers}});if(!response.ok)throw new Error(await response.text());return response.status===204?null:response.json();}
 async function refresh(){const [p,m,s]=await Promise.all([request("/shop-live/v1/products"),request("/shop-live/v1/media"),request("/shop-live/v1/sessions")]);setProducts(p);setMedia(m);setSessions(s);if(!selectedProduct&&p[0])setSelectedProduct(p[0].id);if(!selectedSession&&s[0])setSelectedSession(s[0].id);}
 async function refreshScripts(id=selectedProduct){setScripts(id?await request(`/shop-live/v1/products/${id}/scripts`):[])}
 async function refreshMaterials(id=selectedSession){setMaterials(id?(await request(`/shop-live/v1/sessions/${id}/materials`)).items:[])}
 useEffect(()=>{if(token)void refresh()},[token]); useEffect(()=>{if(token)void refreshScripts()},[selectedProduct]); useEffect(()=>{if(token)void refreshMaterials()},[selectedSession]);
 useEffect(()=>{if(!token)return;const ws=new WebSocket(`${API.replace(/^http/,"ws")}/shop-live/v1/events?token=${encodeURIComponent(token)}`);socket.current=ws;ws.onopen=()=>setState("pronto");ws.onclose=()=>setState("offline");ws.onmessage=e=>{const event=JSON.parse(e.data) as LiveEvent;if(event.type==="operation.context")setContext(event.payload);if(["simulation.started","simulation.resumed"].includes(event.type))setState("executando");if(event.type==="simulation.paused")setState("pausada");if(["simulation.stopped","simulation.completed","simulation.ready"].includes(event.type))setState("pronto")};return()=>ws.close()},[token]);
 function auth(e:FormEvent){e.preventDefault();const clean=draft.trim();if(clean){sessionStorage.setItem("shop_live_token",clean);setToken(clean)}}
 function command(action:"start"|"pause"|"resume"|"stop"){socket.current?.send(JSON.stringify({action,speed:2,session_id:action==="start"?selectedSession:null}))}
 if(!token)return <form onSubmit={auth} className={`${box} mx-auto max-w-md`}><h2 className="text-xl font-bold">Shop LIVE local</h2><input className={input} type="password" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Token do agente"/><button className="rounded bg-emerald-500 p-2 text-zinc-950">Conectar</button></form>;
 return <div className="space-y-4" data-testid="shop-live"><header className="flex flex-wrap justify-between"><div><h2 className="text-2xl font-bold">Shop LIVE · Operação assistida</h2><p className="text-zinc-400">Agente: {state} · nenhuma ação externa</p></div><div className="flex gap-2">{state==="pronto"&&<button onClick={()=>command("start")}>Iniciar</button>}{state==="executando"&&<button onClick={()=>command("pause")}>Pausar</button>}{state==="pausada"&&<button onClick={()=>command("resume")}>Continuar</button>}{["executando","pausada"].includes(state)&&<button onClick={()=>command("stop")}>Encerrar</button>}</div></header>
 <Crud title="Produtos"><ProductForm products={products} request={request} done={refresh}/></Crud>
 <Crud title="Vídeos e áudios autorizados"><MediaForm products={products} media={media} request={request} done={refresh}/></Crud>
 <Crud title="Blocos de roteiro"><select className={input} value={selectedProduct} onChange={e=>setSelectedProduct(e.target.value)}>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ScriptForm productId={selectedProduct} scripts={scripts} request={request} done={()=>refreshScripts()}/></Crud>
 <Crud title="Montagem da sessão"><SessionForm products={products} sessions={sessions} request={request} done={refresh}/><select className={input} value={selectedSession} onChange={e=>setSelectedSession(e.target.value)}>{sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><MaterialForm sessionId={selectedSession} media={media} materials={materials} request={request} done={()=>refreshMaterials()}/></Crud>
 <section className={box}><h3 className="font-bold">Contexto ativo</h3><p>Produto atual: {context.current_product?.name||"—"}</p><p>Próximo produto: {context.next_product?.name||"—"}</p><p>Roteiro: {(context.scripts||[]).map((s:Script)=>s.text).join(" · ")||"—"}</p></section></div>;
}
function Crud({title,children}:{title:string;children:ReactNode}){return <section className={box}><h3 className="mb-3 text-lg font-bold">{title}</h3>{children}</section>}
function ProductForm({products,request,done}:{products:Product[];request:any;done:()=>void}){const [edit,setEdit]=useState<Product|null>(null),[name,setName]=useState(""),[price,setPrice]=useState("0"),[category,setCategory]=useState("");async function save(e:FormEvent){e.preventDefault();await request(edit?`/shop-live/v1/products/${edit.id}`:"/shop-live/v1/products",{method:edit?"PUT":"POST",body:JSON.stringify({name,price:Number(price),category,approved_answers:[],prohibited_claims:[]})});setEdit(null);setName("");done()}return <><form onSubmit={save} className="flex flex-wrap gap-2"><input className={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Produto" required/><input className={input} value={category} onChange={e=>setCategory(e.target.value)} placeholder="Categoria"/><input className={input} type="number" value={price} onChange={e=>setPrice(e.target.value)}/><button>{edit?"Salvar edição":"Cadastrar"}</button></form>{products.map(p=><Row key={p.id} text={`${p.name} · R$ ${p.price}`} edit={()=>{setEdit(p);setName(p.name);setPrice(String(p.price));setCategory(p.category)}} remove={async()=>{await request(`/shop-live/v1/products/${p.id}`,{method:"DELETE"});done()}}/>)}</>}
function MediaForm({products,media,request,done}:{products:Product[];media:Media[];request:any;done:()=>void}){const [edit,setEdit]=useState<Media|null>(null),[product,setProduct]=useState(""),[kind,setKind]=useState("video"),[name,setName]=useState(""),[path,setPath]=useState(""),[duration,setDuration]=useState("60");async function save(e:FormEvent){e.preventDefault();await request(edit?`/shop-live/v1/media/${edit.id}`:"/shop-live/v1/media",{method:edit?"PUT":"POST",body:JSON.stringify({product_id:product||null,kind,name,local_path:path,duration_seconds:Number(duration),authorized:true,authorization_source:"Confirmado pelo operador"})});setEdit(null);setName("");done()}return <><form onSubmit={save} className="flex flex-wrap gap-2"><select className={input} value={kind} onChange={e=>setKind(e.target.value)}><option>video</option><option>audio</option></select><select className={input} value={product} onChange={e=>setProduct(e.target.value)}><option value="">Sem produto</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={input} value={name} onChange={e=>setName(e.target.value)} placeholder="Nome" required/><input className={input} value={path} onChange={e=>setPath(e.target.value)} placeholder="Caminho local autorizado" required/><input className={input} type="number" value={duration} onChange={e=>setDuration(e.target.value)}/><button>{edit?"Salvar":"Cadastrar"}</button></form>{media.map(m=><Row key={m.id} text={`${m.kind} · ${m.name} · ${m.duration_seconds}s`} edit={()=>{setEdit(m);setProduct(m.product_id||"");setKind(m.kind);setName(m.name);setPath(m.local_path);setDuration(String(m.duration_seconds))}} remove={async()=>{await request(`/shop-live/v1/media/${m.id}`,{method:"DELETE"});done()}}/>)}</>}
function ScriptForm({productId,scripts,request,done}:{productId:string;scripts:Script[];request:any;done:()=>void}){const [edit,setEdit]=useState<Script|null>(null),[text,setText]=useState(""),[position,setPosition]=useState("0"),[duration,setDuration]=useState("60");async function save(e:FormEvent){e.preventDefault();await request(edit?`/shop-live/v1/scripts/${edit.id}`:"/shop-live/v1/scripts",{method:edit?"PUT":"POST",body:JSON.stringify({product_id:productId,kind:"apresentacao",position:Number(position),duration_seconds:Number(duration),text})});setEdit(null);setText("");done()}return <><form onSubmit={save} className="flex flex-wrap gap-2"><input className={input} value={text} onChange={e=>setText(e.target.value)} placeholder="Texto aprovado" required/><input className={input} type="number" value={position} onChange={e=>setPosition(e.target.value)}/><input className={input} type="number" value={duration} onChange={e=>setDuration(e.target.value)}/><button>{edit?"Salvar":"Adicionar bloco"}</button></form>{scripts.map(s=><Row key={s.id} text={`${s.position}. ${s.text} · ${s.duration_seconds}s`} edit={()=>{setEdit(s);setText(s.text);setPosition(String(s.position));setDuration(String(s.duration_seconds))}} remove={async()=>{await request(`/shop-live/v1/scripts/${s.id}`,{method:"DELETE"});done()}}/>)}</>}
function SessionForm({products,sessions,request,done}:{products:Product[];sessions:Session[];request:any;done:()=>void}){const [title,setTitle]=useState(""),[selected,setSelected]=useState<string[]>([]);async function save(e:FormEvent){e.preventDefault();await request("/shop-live/v1/sessions",{method:"POST",body:JSON.stringify({title,estimated_minutes:30,seed:42,product_ids:selected})});setTitle("");done()}return <><form onSubmit={save} className="flex flex-wrap gap-2"><input className={input} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Título da sessão" required/>{products.map(p=><label key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>setSelected(old=>old.includes(p.id)?old.filter(id=>id!==p.id):[...old,p.id])}/>{p.name}</label>)}<button>Criar sessão</button></form><p className="text-sm text-zinc-400">{sessions.length} sessão(ões) cadastrada(s).</p></>}
function MaterialForm({sessionId,media,materials,request,done}:{sessionId:string;media:Media[];materials:Material[];request:any;done:()=>void}){const [selected,setSelected]=useState("");async function add(){if(!selected)return;const next=[...materials,{media_id:selected,position:materials.length,planned_duration_seconds:media.find(m=>m.id===selected)?.duration_seconds||60}];await request(`/shop-live/v1/sessions/${sessionId}/materials`,{method:"PUT",body:JSON.stringify(next)});setSelected("");done()}async function move(index:number,delta:number){const next=[...materials];[next[index],next[index+delta]]=[next[index+delta],next[index]];await request(`/shop-live/v1/sessions/${sessionId}/materials`,{method:"PUT",body:JSON.stringify(next.map((m,i)=>({...m,position:i})))});done()}return <div><select className={input} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecionar mídia</option>{media.filter(m=>m.authorized&&!materials.some(x=>x.media_id===m.id)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><button onClick={add}>Adicionar</button>{materials.map((m,i)=><div key={m.media_id} className="flex gap-2 p-2"><span>{i+1}. {media.find(x=>x.id===m.media_id)?.name} · {m.planned_duration_seconds}s</span><button disabled={!i} onClick={()=>move(i,-1)}>↑</button><button disabled={i===materials.length-1} onClick={()=>move(i,1)}>↓</button></div>)}</div>}
function Row({text,edit,remove}:{key?:string;text:string;edit:()=>void;remove:()=>void|Promise<void>}){return <div className="mt-2 flex items-center justify-between rounded bg-zinc-950 p-2"><span>{text}</span><span className="flex gap-2"><button onClick={edit}>Editar</button><button onClick={remove}>Excluir</button></span></div>}
