import { BrowserRouter, Routes, Route } from "react-router";
import { AuthWrapper } from "./components/AuthWrapper";
import { Layout } from "./components/Layout";
import { Home } from "./pages/Home";
import { Configuracao } from "./pages/Configuracao";
import { Canais } from "./pages/Canais";
import { Historico } from "./pages/Historico";
import { Cortes } from "./pages/Cortes";
import { ShopLive } from "./pages/ShopLive";
import { CampanhasCortes } from "./pages/CampanhasCortes";
import { CanaisPublicacao } from "./pages/CanaisPublicacao";
import { ImportarAdaptar } from "./pages/ImportarAdaptar";
import { CommerceStudio } from "./pages/CommerceStudio";
import { KwaiCut } from "./pages/KwaiCut";
import { TikTok } from "./pages/TikTok";
import { Perfis } from "./pages/Perfis";
import { Contas } from "./pages/Contas";
import { Fila } from "./pages/Fila";
import { Metricas } from "./pages/Metricas";
export default function App(){return <BrowserRouter><AuthWrapper><Routes><Route path="/" element={<Layout/>}><Route index element={<Home/>}/><Route path="configuracao" element={<Configuracao/>}/><Route path="canais" element={<Canais/>}/><Route path="historico" element={<Historico/>}/><Route path="cortes" element={<Cortes/>}/>{import.meta.env.VITE_SHOP_LIVE_ENABLED==="true"&&<Route path="shop-live" element={<ShopLive/>}/>} {import.meta.env.VITE_CAMPAIGNS_ENABLED==="true"&&<Route path="campanhas-cortes" element={<CampanhasCortes/>}/>} {import.meta.env.VITE_MULTICHANNEL_ENABLED==="true"&&<Route path="canais-publicacao" element={<CanaisPublicacao/>}/>} {import.meta.env.VITE_IMPORT_ENABLED==="true"&&<Route path="importar-adaptar" element={<ImportarAdaptar/>}/>} {import.meta.env.VITE_COMMERCE_ENABLED==="true"&&<Route path="commerce-studio" element={<CommerceStudio/>}/>}<Route path="kwai-cut" element={<KwaiCut/>}/><Route path="tiktok" element={<TikTok/>}/><Route path="perfis" element={<Perfis/>}/><Route path="contas" element={<Contas/>}/><Route path="fila" element={<Fila/>}/><Route path="metricas" element={<Metricas/>}/></Route></Routes></AuthWrapper></BrowserRouter>}
